### ISSUE TITLE
Stylesheet missing on macOS 10.15

### ISSUE THREAD

**Issue by Jollywatt** [gitbutlerapp/gitbutler#2613]
Freshly installing GitButler from https://app.gitbutler.com/downloads/release/darwin/x86_64/dmg, Version 0.10.6 (20240212.175429), leads to this:

<img width="1028" alt="Screen Shot 2024-02-13 at 6 02 20 PM" src="https://github.com/gitbutlerapp/gitbutler/assets/24970860/50031c80-ecf4-4972-8c40-69fd90f3c67c">

😬
Tested on a couple MacBooks running macOS 10.15.6 and 10.15.7.

Not sure what diagnostics I can include, but can provide anything if requested.

**Comment by mtsgrd** [comment]
It looks to me like not all css is missing, but specifically things that are tied to custom css properties. This includes e.g. all colors, and most of the spacing, but not other things like flex boxes and font family. Not sure how to debug this, css custom properties seem to have been supported since ~2016. 🤨

**Comment by lbittner-pdftron** [comment]
+1 seeing same issue on iOS 12.0.1 on Apple Silicon. Was excited to try this out so hopefully can be resolved soon!

**Comment by r-tae** [comment]
This is caused by `::backdrop` ([here](https://github.com/gitbutlerapp/gitbutler/blob/af02c7cb158945b7a5d6d1598a01ba9c6d97b160/gitbutler-ui/src/styles/tokens.css#L8), and in a couple other places). Webkit only supports it without a prefix [since Jan 2024](https://caniuse.com/?search=backdrop), most people aren't updated yet.

**Comment by lbittner-pdftron** [comment]
Just another update, the top of the UI being cut off is fixed in 0.10.14, but those weird "Apply" here buttons still persist. Additionally, I cannot drag files between branches anymore, making the product unusable.

**Comment by lbittner-pdftron** [comment]
Just a heads up that I created a new issue with the button bugs as I think the problem of the stylesheet not being loaded at all has been resolved. New ticket is here - https://github.com/gitbutlerapp/gitbutler/issues/2878

**Comment by PavelLaptev** [comment]
@Jollywatt thank you for the report! I'm reviewing issues that related to UI.
Is this still relevant?

**Comment by Jollywatt** [comment]
@PavelLaptev I’m still having problems in v0.11.1, but they're better described by #2878. Unfortunately, that ticket was closed because he switched machines, but the bug remains on macOS 10.15.6 and 10.15.7.

We should be able to close this issue — but we should reopen #2878.

**Comment by PavelLaptev** [comment]
Thanks @Jollywatt! I'll take a look at https://github.com/gitbutlerapp/gitbutler/issues/2878.
