### ISSUE TITLE
Branch button no longer opens branch in browser

### ISSUE THREAD

**Issue by fgLouro** [gitbutlerapp/gitbutler#4558]
### Version

0.12.16

### Operating System

Mac OS X

### Distribution Method

dmg (Apple Silicon)

### Describe the issue

Usually the button `origin/<branch-name>` would open a new tab on my browser to my branch inside of my repository. Now it seems to no longer work.

Clicking on the button doesn't do anything. Maybe coming from the last update or the one before that. Only notice it this week.

<img width="289" alt="Screenshot 2024-07-31 at 15 00 49" src="https://github.com/user-attachments/assets/11b4ebf6-a685-4fd7-a259-dbecf59d09c0">

### How to reproduce

Apply branch that has an remote branch and try to click the button.

### Expected behavior

Clicking on the button should open a web page to the repository in the correct branch

**Comment by Caleb-T-Owens** [comment]
Hey! Thanks for reporting! I'm working on a fix for that now 👍

**Comment by fgLouro** [comment]
Hey @Caleb-T-Owens, sorry to bother you, but was this PR #4634 that was released with `v0.12.19` related to this issue?

**Comment by Caleb-T-Owens** [comment]
Hi @fgLouro, yes! It should be resolved now. Feel free to reopen if you find any edge cases

**Comment by fgLouro** [comment]
It still not working for me. I didn't mention in the issue but i'm using Gitlab, which should be an issue because it worked before. 

Is there anything I can provide you to better debug this?

**Comment by Caleb-T-Owens** [comment]
@fgLouro I've just tried it out and noticed that I need to have the github integration set up to see the link, but once that is done, it works as expected.

I'm going to re-open the issue as that is not intended, but if you could confirm that that is also the case for you, that would be appreciated

<img width="638" alt="Screenshot 2024-08-15 at 16 36 25" src="https://github.com/user-attachments/assets/b651d8bf-09f5-4633-8c82-98eb8206009c">

**Comment by fgLouro** [comment]
I can confirm that it does work when the Github integration is connect to a Github repository.

**Comment by ndom91** [comment]
@fgLouro it should work with Gitlab URLs with the latest releases as well :+1:

**Comment by fgLouro** [comment]
Sorry but it is not working. 

I setup the project to run locally to debug the issue and the `gitHostBranch` is always undefined. 

This is in the `BranchPreviewHeader.svelte`
![Screenshot 2024-08-16 at 12 56 52](https://github.com/user-attachments/assets/f1445fa3-15a4-41c5-9e79-3e5f5d7f2008)




Also when I apply the branch it is the same issue

This is in the `ActiveBranchStatus.svelte`
![Screenshot 2024-08-16 at 12 58 53](https://github.com/user-attachments/assets/d3c5b3f2-f54d-4533-8a8b-1c402870c8ff)


If I replace `const url = gitHostBranch?.url;` with a hard coded url it works.

https://github.com/user-attachments/assets/178e43fa-d303-4bcb-bc8e-b617dd8754d1



Can this be an issue with my git configuration if so what should I look at?

**Comment by fgLouro** [comment]
After further digging I found that the `DefaultGitHostFactory` build function is not having into account the gitlab instances that are self hosted.

Here is the `repo` sent to the build function:
![Screenshot 2024-08-16 at 13 23 04](https://github.com/user-attachments/assets/60b082f8-17e1-4c46-b088-9505246258f1)

The problem is that gitbutler is assuming that the gitlab domains always ends with `gitlab.com`, when self host instances of gitlab have the format `gitlab.{domain}`

My guess is that the issue was introduced in this commit: https://github.com/gitbutlerapp/gitbutler/commit/e1f9c8b59e8518c8c15534cae0769dd7acf8dc07
