### ISSUE TITLE
"there is no default target" when adding local repository

### ISSUE THREAD

**Issue by sentience** [gitbutlerapp/gitbutler#9505]
### Version

0.15.3

### Operating System

macOS

### Distribution Method

dmg (Mac OS - Apple Silicon)

### Describe the issue

Adding an existing Git working copy on my machine to GitButler, I'm getting multiple error pop-ups with the same message:

```
command: list_branches
params: {"projectId":"ba0b28ad-32ec-4b18-8b82-5f9975974e6c"})

there is no default target
```

The onboarding screen (i.e. select a workspace target branch) for the newly-added repo did not appear as expected.

The repo in question has the `main` branch checked out with unstaged changes. This branch is set to track `origin/main`. There is also a `master` branch in the local repository, set to track `origin/master`, which has been deleted on the remote.

In an effort to troubleshoot this, I deleted the local `master` branch and then restarted GitButler. This time, the app correctly showed the onboarding (select a workspace target branch) screen, but three more instances of the error above also appeared in pop-ups. I selected the `origin/main` branch as my target, and from there GitButler behaved normally again.

### Relevant log output (Optional)

```shell

```

**Comment by Byron** [comment]
Thanks a lot for reporting, and I am glad that you could get it to work in the end without having much of an intuition as to what could have caused this.

However, we as we are overhauling the respective systems I would expect this issue to disappear - after all, target branches will be optional in future so no configuration is required to get started.

**Comment by krlvi** [comment]
@sentience Thanks for taking the time to report this. This particular issue is a new regression - apologies for this, we will have this fixed today in a new patch release

**Comment by krlvi** [comment]
This should be resolved now in 0.15.4

**Comment by RavenHogWarts** [comment]
**Version 0.15.3 reports the following error:**  
```  
command: list_branches  
params: {"projectId":"89086e53-247f-4ba9-98fa-5f66f17d291d"})  
there is no default target  
```  
**In version 0.15.4, although no error is reported, it still fails to create and gets stuck at 'Let's Go'."**

**Comment by mamanin** [comment]
I have the same issue as @RavenHogWarts:

Since the 0.15.4, I cannot register a new repository, after selecting the "Target branche", when clicking on the "Lets Go" button nothing happened.

When arriving on the page, I have this error:
```
command: stack_details
params: {"projectId":"e1a366da-2457-4439-8ec2-caf7bbd3bd40","stackId":"2de377b4-7c83-4170-93e8-acf64fabf4fd"})

branch with ID 2de377b4-7c83-4170-93e8-acf64fabf4fd not found
```

**Comment by RavenHogWarts** [comment]
I temporarily rolled back to [0.15.2](https://releases.gitbutler.com/releases/release/0.15.2-2186/windows/x86_64/GitButler_0.15.2_x64_en-US.msi)

**Comment by slingshotsys** [comment]
In `0.15.4` no toast is displayed but the same error shows up in the console:

<img width="1051" height="312" alt="Image" src="https://github.com/user-attachments/assets/919621c8-8f78-4ec5-9c0a-cdbfabee3061" />

**Comment by Byron** [comment]
I think this would be expected with the way this is currently implemented - the error popup is just suppressed while no target is set.

This will be improved soon when the new backend is used by default.

In any case, there should be no issue with this anymore, and a new project can be added without error popups, right?

**Comment by slingshotsys** [comment]
Issue still persists for me, I am unable to add a new workspace in 0.15.4 on Windows.  The "Open project" and/or "Let's go" button do nothing, and in the developer console I get the `there is no default target` error.

Unless it has been fixed in the nightly? I haven't tested that.

**Comment by Byron** [comment]
Nightly is always the best bet as it gets auto-generated every couple of hours. The downloads [are here](https://gitbutler.com/downloads), and it will auto-update itself as well.

**Comment by alex14563** [comment]
In 0.19.10,stuck at the lets go page

<img width="624" height="601" alt="Image" src="https://github.com/user-attachments/assets/bea9cd3a-999e-42e7-a7e9-c661ecba86e2" />

**Comment by Byron** [comment]
Thanks for sharing.

At this point, it is entire entirely unclear to me how the default target can be missing in a repository that was initialized.
And maybe it wasn't initialized and some code runs too early and the user interface doesn't catch that.
I found something that *might* be related, and the only way for you to find out it's getting better is to use the [Nightly](https://gitbutler.com/nightly) build.

**Comment by krlvi** [comment]
Thanks everyone for the reports here. This thread ended up covering a few separate regressions with the same symptom:

- The original `there is no default target` errors were fixed in https://github.com/gitbutlerapp/gitbutler/pull/9508 and shipped in `0.15.4`.
- The Windows-specific “Let’s go” failure was fixed in https://github.com/gitbutlerapp/gitbutler/pull/9550 and shipped in `0.15.5`.
- The recurrence reported on `0.19.10` was addressed by https://github.com/gitbutlerapp/gitbutler/pull/13829, shipped in `0.19.12`, with further target-handling cleanup in https://github.com/gitbutlerapp/gitbutler/pull/13821 in `0.19.13`.

Current releases include all of these fixes, so I’m closing this as fixed. If this still happens on `0.21.0` or newer, please open a fresh issue with the logs and we’ll take another look.
